services:
  - type: web
    name: my-web-service
    env: php
    plan: free
    buildCommand: |
      ./install-composer.sh
      composer install
    startCommand: php artisan serve --host 0.0.0.0 --port 10000
